version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_spring_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: aeroTechDB
    ports:
      - "3306:3306"
    networks:
      - app-network

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kotlin_app
    env_file:
      - .env
#    environment:
#      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
#      SECURITY_JWT_EXPIRATION: ${SECURITY_JWT_EXPIRATION}
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

